### ISSUE TITLE
A bunch of errors

### ISSUE THREAD

**Issue by zeshanshani** [tutsplus/so-you-bought-a-mac#1]
Thanks for the script. Unfortunately, after inserting it using the same method as Jeffrey described, it's giving me a bunch of errors. Most of them are "command not found" A screenshot is this: http://prntscr.com/6bayj3

Not sure what could be the issue, could you please check and fix?

Thanks!

**Comment by zeshanshani** [comment]
Ok, so half of it is fixed, the script is using double pretty quotes, that's causing the issue.

Now the only two issues are left which are in line #5

`-bash: /Users/zeshan/.bash_profile: line 35: syntax error near unexpected token `('
-bash: /Users/zeshan/.bash_profile: line 35: `  [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo "*"'`

**Comment by zeshanshani** [comment]
gotcha, these errors are due to the pretty quotes instead of normal double quotes.

**Comment by maxwellflood** [comment]
Hey Zeshan just having the same issue you were, can you remember which quotation marks were the issue?

**Comment by zeshanshani** [comment]
@Maxwell- Yes I have already sent a pull request here #2
